### ISSUE TITLE
Change DNS

### ISSUE THREAD

**Issue by Malwine** [ClojureBridge/clojurebridge.github.io#27]
Change the DNS to point clojurebridge.org to this GitHub Pages repository

**Comment by davidchambers** [comment]
[Setting up an apex domain][1] is the relevant guide, I believe. @yokolet, would you like to arrange a time for the two of us to make these changes together or are you comfortable making these changes yourself?


[1]: https://help.github.com/articles/setting-up-an-apex-domain/

**Comment by yokolet** [comment]
@davidchambers Now, DNS is pointing github pages. I see "Previous Events" section at clojurebridge.org

Please check :smiley:

FYI: the repo already got CNAME file. That's why requests to clojurebridge.github.io was redirected to clojurebridge.org

**Comment by davidchambers** [comment]
Works for me! Thank you, Yoko!
