### ISSUE TITLE
determine whether "map error" is detectable

### ISSUE THREAD

**Issue by davidchambers** [ClojureBridge/clojurebridge.github.io#41]
<https://github.com/ClojureBridge/clojurebridge.github.io/pull/33#issuecomment-296771263>:

> If they forget latitude and longitude or don't know how to do it: Could we display a grey area/div? Because otherwise we get this "map error" thing which is not so nice 😰 :
![screen shot 2017-04-24 at 19 46 37](https://cloud.githubusercontent.com/assets/5123681/25350864/dcb0cd4e-2926-11e7-8e9c-48e269812dad.png)

**Comment by vsmart** [comment]
I see that the latitude/longitude values as min/max are encoded in the `validate-file` logic : 
https://github.com/ClojureBridge/clojurebridge.github.io/blob/master/validate-yaml.cljs#L20-L21

I think this means that the build would fail if incorrect values are given and that we can close here. cc @davidchambers

**Comment by davidchambers** [comment]
Good point, Franka. :)
