### ISSUE TITLE
Google Maps error

### ISSUE THREAD

**Issue by fabrgu** [ClojureBridge/clojurebridge.github.io#60]
The following error displays when trying to display google maps in the blog posts: this page didn’t load google maps correctly.

**Comment by davidchambers** [comment]
Are you referring to an event on the website, @fabrgu, or to #62?

**Comment by fabrgu** [comment]
All the events on the website that are using google maps. For example: https://clojurebridge.org/events/2017-11-17-london
and
https://clojurebridge.org/events/2017-09-22-melbourne-au

**Comment by davidchambers** [comment]
It seems Google has changed their pricing. From [Maps Static API Usage and Billing][1]:

> __Reminder:__ To use our Maps, Routes, and Places APIs:
>
>   - All Google Maps Platform API requests must include an API key; we no longer support keyless access.
>   - You must [enable billing][2] on each of your projects.

This is quite annoying. We should see whether there's a free alternative.


[1]: https://developers.google.com/maps/documentation/maps-static/usage-and-billing
[2]: 
https://console.cloud.google.com/project/_/billing/enable?redirect=https://developers.google.com/maps/documentation/maps-static/usage-and-billing?dialogOnLoad%3Dbilling-enabled

**Comment by vsmart** [comment]
We should use Mapbox for this. The free tier should be enough for our views.
